### ISSUE TITLE
4.5GB file generated

### ISSUE THREAD

**Issue by AlexandrosMelissas** [Prayag2/konsave#102]
Is this normal?

**Comment by ben2talk** [comment]
With no context, impossible to say.

I have noticed, when exporting a profile, it tends to export the entire Kvantum folder along with all of it's contents.

Mostly it saves configurations (rc) files which will only work on the source system, it does not include also every icon theme referenced, for example.

For my 'Dark' profile, this can be zipped up to a 1GiB archive.

If you 'Export' a profile, then all items selected to be saved will not simply be referenced, but the original icons and everything else will be included in that 'Export' file to be sent elsewhere and used on some other machine.

I am now testing this for the first time - and it is taking (IMO) longer than it's worth... and rather than a 1GiB tar.gz file which I can use on my system, it exports a ZIP file which totals 2.0GiB.

So yes, it's normal for an EXPORTED.knsv profile to contain a lot more data than a simple saved profile.

It will include your `.fonts` and `.icons` and `.themes` folders, and also (more bloatedly) your `share_folder` with MORE fonts/icons/plasma/wallpapers.

**Comment by Prayag2** [comment]
This totally depends on your config files and this will, in most cases, happen only when you "export" the profile, since then your icon packs, fonts etc are also exported. You can edit the config file in `~/.config/konsave/conf.yaml` to remove things from getting backed up if you want!
