### ISSUE TITLE
Does not copy Background or Autostart apps

### ISSUE THREAD

**Issue by Samisafool** [Prayag2/konsave#54]
**Describe the bug**
Does not copy Background or Autostart apps

**To reproduce**
1. Make a VM
2. Apply an exported profile
3. Logout and Login
4. Wallpaper is the default one
5. Autostart is empty in System Settings

**Expected behavior**
It should copy over the Autostart and Wallpaper

**Screenshots**

**System information**
 - **OS or Linux distribution:** Arch
 - **How did you install Konsave?** Pip, AUR one is broken
 - **What version of Konsave are you using? Did you try updating?** 2.1.1 on both exporter and VM

**Additional context**

**Comment by Prayag2** [comment]
It's currently not possible to copy the wallpaper. Konsave works by backing up config files. To copy the wallpaper, it would need to read the config file and extract the location of the wallpaper. I can, however, make it copy all the wallpapers stored in `~/.local/share/wallpaper` directory.

Also, it does not make sense to include the autostart file because different people have different preferences about what program should start automatically and what shouldn't. If you want to add autostart to Konsave, you can do it easily for your configs. Follow these steps if you want to add Autostart  and wallpapers to your config files:

1. Open `~/.config/konsave/conf.yaml`
2. add `- autostart` below line 40.
3. add `- wallpapers` below line 85
And then you're done.
Adding custom files and folders to konsave is also mentioned in the README so make sure you read it.

**Comment by Samisafool** [comment]
> Also, it does not make sense to include the autostart file because different people have different preferences about what program should start automatically and what shouldn't.

Well, if they go as far as to use my config. they can just remove it lol...

> Adding custom files and folders to konsave is also mentioned in the README so make sure you read it.

I did, it's just that I thought this would be better as a default.

Anyway, I got your point, so do I close this?

**Comment by Prayag2** [comment]
> Anyway, I got your point, so do I close this?

Nah don't close it. I think I'll add the wallpapers folder. Thanks!
