### ISSUE TITLE
[Question] Why does konsave save gtkrc?

### ISSUE THREAD

**Issue by Samisafool** [Prayag2/konsave#59]
It is autogenerated by kde plasma, it does not make much sense to save it.

**Comment by Prayag2** [comment]
How is it auto generated? I need to know more.

**Comment by Samisafool** [comment]
```bash
% cat .config/gtkrc
# created by KDE Plasma, Mon Apr 25 09:22:05 2022
#
```

**Comment by Prayag2** [comment]
But what if I change the gtk theme myself? The preferences will be stored in this file right?

**Comment by MichaelTunnell** [comment]
I do think it makes sense to save it because KDE Plasma has configuration options for GTK. There is a weird misconception about GTK vs Qt in the Linux community. People think Qt is bad because it looks weird in GNOME and GTK is good because it looks good in KDE Plasma. The truth of this is that GNOME does nothing to make Qt look good so it doesnt where as KDE does put effort in making GTK look good in Qt based Plasma. It isnt an issue of GTK vs Qt but rather effort being made by KDE vs none by GNOME. With that said, there is a reason to have GTK config files because KDE is creating those files for these reasons.
