### ISSUE TITLE
Change log file location as it clutters the home directory.

### ISSUE THREAD

**Issue by Prayag2** [Prayag2/konsave#62]
Need to change the location of the log file which is automatically generated when an error occurs in Konsave. The new location would be: `~/.config/konsave/logs/<date of creation>.txt`.

**Comment by ralacerda** [comment]
Hi @Prayag2 

Do you mind if I work on this issue since is labeled `good first issue`?

Also, maybe the new location should be:
`~/.local/state/konsave/logs/<time string>.txt` 

Since is the folder specified by [freedesktop](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html) for logs.

**Comment by will-ca** [comment]
> Also, maybe the new location should be:
> `~/.local/state/konsave/logs/<time string>.txt`

If you're gonna make a new location, maybe `.cache` or `.var` would be better for non-essential log files. `.cache` if you want to follow the spec you linked, `.var` if you want to follow Unix root convention analogies.

**Comment by Prayag2** [comment]
@ralacerda I'm sorry I was busy with exams so I couldn't reply. Yes, please feel free to make a pull request :)
I can't work on it for 5-6 months because I still have exams but I'll make sure to test the changes you make and merge your PR :D

**Comment by Prayag2** [comment]
Fixed.
