### ISSUE TITLE
Optimization file size

### ISSUE THREAD

**Issue by aemonge** [Prayag2/konsave#81]
**Is your feature request related to a problem? Please describe.**
The problem is when uploading the file to github. Git maxes at 100mb, and my current file is now 150MB; which in my mind is huge, but I don't know.

**Describe the solution you'd like**
Probably I have a lot of images, or big file settings, so I would love to understand how can I check the files that are making this file so big

**Comment by Prayag2** [comment]
The file size depends on the config files you save. By default, icon packs are also exported. If you have a lot of icons installed, or a large icon pack, the file can take upto 200mb easily. You may need to edit the config file or remove the unused icon packs manually.

**Comment by aemonge** [comment]
Furthermore, I've removed a ton of wallpapers and icons, but the size is still big. I understand making it slim it hard, but I would be ideal just to understand what is making the file that big, and print the location of the big directories, so that we (if we want) delete file from there.

**Comment by ben2talk** [comment]
I'm confused why I see 'Rowaita-icon-theme' there... indeed an incredible collection of more fonts than I see in my settings. It seems that some icons which I no longer see in KDE are located in ~/.local/share/ folder (imported as `share_folder`).

Upon removing from the ORIGINAL folder those files which I no longer require, and so do not wish exported, I managed to repeat the export with an 83MiB export file.

So indeed, the 'error' of Konsave scraping too many files together is probably due to the existence of files you are not even aware of - and will find inside that knsv file.

Remember, no use deleting from the knsv - you must clean up the system.
