### ISSUE TITLE
How to install on Kubuntu?

### ISSUE THREAD

**Issue by methanoid** [Prayag2/konsave#83]
"python -m pip install konsave" is supposed to work but doesnt work for me on Kubuntu 23.04.... 

Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3

So tried 
"python3 -m pip install konsave"

"error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install."

I'm sure its easy fix but nothing came up on Google

**Comment by Prayag2** [comment]
Make sure python is installed and it's in your `PATH`. First of all, try using `python3` instead of `python`. If you still can't find it, try doing `sudo apt install python3`.

If you're sure that it's installed, try adding it to your path by adding-
`export PATH="/usr/bin/python3/:$PATH"` to your `~/.bashrc` or `~/.zshrc` if that's what you're using.

**Comment by TheOverpassArsonist** [comment]
This should be solvable using python virtual environments. Specifically
`python -m virtualevn ./NEWVENV`
and then (I think)
`source ./NEWVENV/bin/activate`
then you can install python packages like normal

Honestly though, it might just be because I'm a bit echo-chambered but I find it weird that it can _**ever**_ be installed without doing this. I was under the impression that since all distros use package managers all distros' python installations would be 'externally managed'. I know personally I've basically been using arch derivatives from day 1 (and raw arch, albiet to a **_very_** limited extent, just wasn't worth the faff) and I've always had to use virtual envs, always heard of people having to use venvs, etc. 

For anyone else coming across this, there **_does_** appear to be an [AUR package](https://aur.archlinux.org/packages/konsave) for konsave but it looks to be unofficially maintained so use at your own risk. It does seem to be well maintained, but it's still a third party so there's always that additional risk.
