### ISSUE TITLE
Feature parity with SaveDesktop

### ISSUE THREAD

**Issue by sbstn87** [Prayag2/konsave#94]
Hi,

will it be possible to achieve feature parity with a GUI app called Save Desktop?

Link to repo:
https://github.com/vikdevelop/SaveDesktop

It is written in Python, so maybe it will be possible to easily port its functionality to konsave?

**Comment by sbstn87** [comment]
It would be nice if konsave could backup by default: 
- icons, fonts, and themes
- KDE system settings (like double click behaviour, screesaver, blue light filter, etc.)
- wallpapers
- Plasma widgets

**Comment by ben2talk** [comment]
> It would be nice if konsave could backup by default:
> 
>     * icons, fonts, and themes
> 
>     * KDE system settings (like double click behaviour, screesaver, blue light filter, etc.)
> 
>     * wallpapers
> 
>     * Plasma widgets

Did you read the documentation? 

Specifically, go to the 'code' page and find out about the config.yaml file, then read that file?

You need to be specific.

AFAIK Widgets and their settings are saved, as are most plasma configuration files.

Icons and fonts and themes would be copied if you export - otherwise they're part of the system and so just information about what is selected is all that's needed.

**Comment by Prayag2** [comment]
Almost everything that you have mentioned is backed up by default. I can't say if settings like double click behavior, blue light filter are backed up but you can test if you'd like. Feel free to open the issue again if you'd like some more things to be backed up by default!
